### ISSUE TITLE
Micro Row's main sprites won't show up on the editor

### ISSUE THREAD

**Issue by meuol** [rhmodding/bread#10]
![image](https://user-images.githubusercontent.com/22159183/93720555-6d1fa500-fb4f-11ea-8e87-0167aca739f8.png)
Sprite shown is sprite 56. Error occurs on all versions of Micro Row (1, 2, remix4 and 2P)

Files:
[ver0.zip](https://github.com/rhmodding/bread/files/5252475/ver0.zip)

**Comment by chrislo27** [comment]
Cannot reproduce. All sprite parts for sprite 56 have opacity 0, so it is entirely transparent as expected.

**Comment by meuol** [comment]
That does seem to be the case. It probably has something to do with how the game handles transparency.
It does make it unintuitive to edit and add new parts though, but it seems to be the excepted behaviour of the file
