### ISSUE TITLE
[Feature Request] Export animation as a frame sequence

### ISSUE THREAD

**Issue by CebolaBros64** [rhmodding/bread#13]
From #7 :

> Today the subject of Bread's animation exporting came on RHModding, and we were discussing how transparency is an issue with both current formats: MP4 has none, and GIF is always either 100% or 0% alpha, which doesn't play very well with the anti-aliased outlines in a lot of the sprites from the game.
> 
> I'd like to suggest an option to bulk export each individual frame of animation a PNG file. It's lossless and is versatile enough for the end user.

**Comment by chrislo27** [comment]
This feature will be available in the next public release (planned v1.4.0).
