### ISSUE TITLE
Bread refuses to start

### ISSUE THREAD

**Issue by BobTheNerd10** [rhmodding/bread#22]
Self explanatory, opening via the jar file does nothing. Opening via command prompt gives this error

Error: Could not find or load main class rhmodding.bread.Bread
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by chrislo27** [comment]
Please verify you are running with Java 8 to 10 by running `java -version`. Versions 11 and higher are not supported.

**Comment by BobTheNerd10** [comment]
That was the issue, thank you!
