### ISSUE TITLE
[Feature Request] Lossless animation export

### ISSUE THREAD

**Issue by CebolaBros64** [rhmodding/bread#7]
GIFs are very limited when it comes to color pallete and compression, it'd be good to have a lossless alternative to exporting animations.

**Comment by chrislo27** [comment]
MP4 export (not lossless but better than GIF) implemented as of 31903cbdce0fbc78afd0bfb221f2ae552e0b11b0. Release set for v1.2.0.

**Comment by CebolaBros64** [comment]
Sorry for necroposting, but it's technically the same issue so I felt there wasn't the need to make a new one.

Today the subject of Bread's animation exporting came on RHModding, and we were discussing how transparency is an issue with both current formats: MP4 has none, and GIF is always either 100% or 0% alpha, which doesn't play very well with the anti-aliased outlines in a lot of the sprites from the game.

I'd like to suggest an option to bulk export each individual frame of animation a PNG file. It's lossless and is versatile enough for the end user.

**Comment by chrislo27** [comment]
Please open a new issue for this feature request.
